apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: |
    A service for testing Backstage functionality. For example, we can trigger errors
    on the sample-service, these are sent to Sentry, then we can view them in the 
    Backstage plugin for Sentry.
  annotations:
    datadog/dashboard-url: https://p.datadoghq.eu/sb/0btd7eqqecs1876r-bffe383395de51ae6fe70257da1e547f?from_ts=1612163170556&to_ts=1612166770556&live=true 
spec:
  type: service
  owner: david@roadie.io
  lifecycle: experimental
